server:
  #context-path: /client
  port: 8102
  servlet:
    context-path: /client
##dubbo 服务消费者配置
spring:
  dubbo:
    application:
        name: Consumer
    registry:
      address: zookeeper://127.0.0.1:2181
    protocol:
      name: dubbo
    scan: com.spring.client.controller

  http:
      encoding:
        charset: UTF-8
        enabled: true
        force: true
      aop:
        auto: true
#数据源
  datasource:
    druid:
      filters: mergeStat,wall,logback
      initial-size: 5
      max-active: 50
      min-idle: 5
      max-wait: 6000
      validation-query: SELECT 'x'
      test-on-borrow: true
      test-on-return: true
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      remove-abandoned: true
      remove-abandoned-timeout: 1800
      log-abandoned: true
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*'
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: admin
        login-password: 123456
#       #数据源1 业务数据
#      datasource1:
#        url: jdbc:mysql://127.0.0.1:3306/dmm??serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
#        username: root
#        password: 123456
#        driverClassName: com.mysql.jdbc.Driver
      #shiro数据源，用于权限相关
      shiro-data-source:
        #MyISAM和InnoDB是两种最常用的数据库引擎，默认的引擎是MyISAM，性能最好，但不支持事务处理，只有InnoDB支持事务
        url: jdbc:mysql://127.0.0.1:3306/dmm?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
        username: root
        password: 123456
        driverClassName: com.mysql.jdbc.Driver

globalConfig1:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
  idType: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
  fieldStrategy: 2
    #驼峰下划线转换
  dbColumnUnderline: true
    #刷新mapper 调试神器
  refreshMapper: true

global-config-shrio:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
  idType: 3
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
  fieldStrategy: 2
    #驼峰下划线转换
  dbColumnUnderline: true
    #刷新mapper 调试神器
  refreshMapper: true

redis:
  shiro:
    host: 127.0.0.1
    port: 6379
    timeout: 0
    password:

##spring.application.name=dubbo-consumer
#server:
#  context-path: /auth
#  port: 8102
##应用名称
#spring:
#  dubbo:
#    application:
#      name: auth-consumer
##注册中心地址
#    protocol:
#      name: dubbo
#    registry:
#      address: zookeeper://127.0.0.1:2181
##调用dubbo组建扫描的项目路径
#    scan: com.demo.controller
