server:
  port: 8101
#应用名称
spring:
  dubbo: 
    application:
#注册在注册中心的名称，唯一标识，请勿重复
      id: auth-master
      name: auth-master
#注册中心地址，zookeeper集群，启动输出可以看见链接了多个
#单zookeeper服务：zookeeper://127.0.0.1:2181
    registry: 
      address: zookeeper://127.0.0.1:2181
#暴露服务方式
    protocol:
      id: dubbo
#默认名称，勿修改
      name: dubbo
#暴露服务端口 （默认是20880，修改端口，不同的服务提供者端口不能重复） 
      port: 20880
      status : server
#调用dubbo组建扫描的项目路径
    scan: com.spring.server.service.impl

  datasource:
      generate-unique-name: false
      url: jdbc:mysql://127.0.0.1:3306/dmm?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
      initialSize: 1
      minIdle: 1
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      validationQuery: SELECT 1


  #公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
  typeAliasesPackage: com.core.po
  mapperLocations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #显示查询结果








#
##数据源
#  datasource:
#    druid:
#      filters: mergeStat,wall,logback
#      initial-size: 5
#      max-active: 50
#      min-idle: 5
#      max-wait: 6000
#      validation-query: SELECT 'x'
#      test-on-borrow: true
#      test-on-return: true
#      test-while-idle: true
#      time-between-eviction-runs-millis: 60000
#      min-evictable-idle-time-millis: 300000
#      remove-abandoned: true
#      remove-abandoned-timeout: 1800
#      log-abandoned: true
#      web-stat-filter:
#        enabled: true
#        url-pattern: /*
#        exclusions: '*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*'
#      stat-view-servlet:
#        enabled: true
#        url-pattern: /druid/*
#        reset-enable: false
#        login-username: admin
#        login-password: 123456
#       #数据源1 业务数据
#      datasource:
#        url: jdbc:mysql://127.0.0.1:3306/dmm??serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
#        username: root
#        password: 123456
#        driverClassName: com.mysql.jdbc.Driver
#      #shiro数据源，用于权限相关
#      shiro-data-source:
#        #MyISAM和InnoDB是两种最常用的数据库引擎，默认的引擎是MyISAM，性能最好，但不支持事务处理，只有InnoDB支持事务
#        url: jdbc:mysql://127.0.0.1:3306/dmm?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
#        username: root
#        password: 123456
#        driverClassName: com.mysql.jdbc.Driver

#globalConfig1:
#    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
#  idType: 0
#    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
#  fieldStrategy: 2
#    #驼峰下划线转换
#  dbColumnUnderline: true
#    #刷新mapper 调试神器
#  refreshMapper: true
#
#global-config-shrio:
#    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
#  idType: 3
#    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
#  fieldStrategy: 2
#    #驼峰下划线转换
#  dbColumnUnderline: true
#    #刷新mapper 调试神器
#  refreshMapper: true
